version: "3.3"
services:
  ziti-gitlab-webhook:
    build: .
    # image: ghcr.io/openziti/ziti-gitlab-webhook:0.1.0
    restart: always
    environment:
      - ZITI_NODEJS_LOG=3
      - ZITI_LOG=3

    # command: node index.js > ./log/ziti-http-agent.log > 2&1
    # command: bash

    dns:
    - 8.8.8.8
    - 4.4.4.4

    extra_hosts:
    - "curt-edge-controller:10.0.1.3"
    - "curt-edge-router:10.0.1.3"
    - "curt-edge-ws-router:10.0.1.3"
    - "curt-edge-wss-router:10.0.1.3"
    - "curt-fabric-router-red:10.0.1.3"

